name: Backup Repository To S3

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'


jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_GH_BACKUP_ACCESS_KEY_ID }}
          MIRROR_TARGET: jarvisanalytics-github-backup/github/${{ github.event.repository.name }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_GH_BACKUP_SECRET_ACCESS_KEY }}
        with:
          args: --overwrite --remove
